app/api/routes.py
import math
import sqlalchemy as sa
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, flash
from flask_login import current_user, login_required
from models import db, AssessmentComponent, AssessmentScore
from forms import AssessmentScoreForm, ComponentForm, EditAssessmentScoreForm
from app.services.charts import *
from app.services.data_analysis import *
from app.services.api_views import *
import numpy as np

api = Blueprint('api', __name__, url_prefix='/api', template_folder='../templates/api')
templates = Blueprint('templates', __name__)

@api.route('/', methods=['GET', 'POST'])
def data_entry_params():
    """landing page for data entry"""
    if request.method == 'GET':
        return render_data_entry_parameters()
    elif request.method == 'POST':
        return process_data_entry_parameters()
    
@api.route('/data_entry/<string:assessment_name>', methods=['GET', 'POST'])
def data_entry(assessment_name):
    """API endpoint for data entry"""
    period = request.args.get('period')
    if request.method == 'GET':
        return render_data_entry_template(assessment_name, period)
    elif request.method == 'POST':
        return process_data_entry_request(assessment_name, period)


@api.route('/data_entry/edit', methods=['GET', 'POST'])
def edit_data_params():
    """Landing page for editing data"""
    if request.method == 'GET':
        return render_edit_data_parameters()
    elif request.method == 'POST':
        return process_edit_data_parameters()

def render_edit_data_parameters():
    """Parameters for editing score data in database"""
    user = current_user
    current_class = user.get_current_classroom()  # returns classroom object
    class_score_data = get_data(current_class.id)

    assessments = class_score_data['assessment_name'].unique()  # assessments already taken
    periods = {1: 'fall', 2: 'winter', 3: 'spring'}
    available_periods = {assessment:[periods] for assessment in class_score_data['assessment_name'] for period in class_score_data['period']}
    # Create a dictionary to hold available periods for each assessment

    return render_template('edit_data_params.html', assessments=assessments, periods=periods, available_periods=available_periods)

def process_edit_data_parameters():
    print(request.form)
    assessment = request.form.get('assessment')
    period = request.form.get('period')
    if assessment and period:
        return redirect(url_for('api.edit_data', assessment_name=assessment, period=period))
    else:
        flash('Please select both an assessment and a period', 'error')
        return redirect(url_for('api.edit_data_params'))

@api.route('/data_entry/edit/<string:assessment_name>', methods=['GET', 'POST'])
def edit_data(assessment_name):
    """API endpoint for editing data"""
    period = request.args.get('period')
    if request.method == 'GET':
        return render_edit_data_template(assessment_name, int(period))
    elif request.method == 'POST':
        return process_edit_data_request(assessment_name, int(period))



@api.route('/classroom/<string:classroom_id>', methods=['GET', 'POST'])
@login_required
def class_dashboard(classroom_id, method='GET'):
    user=current_user
    current_class = user.get_current_classroom()
    classroom_info = current_class.to_dict()
    data = get_data('21-SPA-0')

    math_data = data[(data.subject == 'math')]
    lit_data = data[(data.subject == 'literacy')]
    math_fun_fig= make_funnel(math_data)
    math_bar_fig = make_bar_fig(math_data)
    lit_fun_fig= make_funnel(lit_data)
    lit_bar_fig = make_bar_fig(lit_data)

    figs = [lit_bar_fig, math_bar_fig, lit_fun_fig, math_fun_fig]

    return render_template(template_name_or_list='class_dashboard.html', classroom_info=classroom_info, classroom_id=current_class, figs=figs)

app/templates/api/class_dashboard.html
{% extends "base.html" %}

{% block content %}
<title>Dashboard</title>
<header class="bg-dark text-white">

    <div class="container d-flex flex-column">
        <br>
        <h1 class="display-6">Insights</h1>
        <!-- could make this a select for teachers w. multiple classes -->
        <p class="lead">{{ classroom_id }}</p>
        <p>Instructor: {{classroom_info.teacher}}</p>


    </header>

<!-- High Level Insights-->
<section>
<div class="container-fluid text-center">
    <br>
    {% for fig in figs %}
    <div class="d-flex flex-row justify-content-md-center">
            <figure class="figure">
                {{ fig | safe }}
            </figure>
            </div>
            {% endfor %}
</section>


{% endblock %}

app/templates/api/data_entry.html
{% extends 'base.html' %}

{% block content %}

<br>
    <!-- FORM -->
    

        <br></br>
        <h1 class="display-6">Data Entry</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            
            <div class="container-fluid">
                
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Student</th>
                        {% for component in components %}
                        <th scope="col"class="text-center">{{ component.component_name }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody >
                    {% for data in roster_data %}
                    <tr>
                        <td scope="row">{{ data.student_name }}</td>
                        {% for component in components %}
                        <td>
                            <input class="form-control form-control-sm" type="number" name="score_{{ data.id }}_{{ component.id }}" value="0.0">
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
            </div>
            <br>
            <div class="d-grid gap-2 d-md-block">
                <button class="btn btn-dark" type="button">Submit</button>
            </div>
            <br></br>
        </form>
    </div>    
</div>
{% endblock %}

app/templates/api/data_entry_params.html
{% extends 'base.html' %}

{% block content %}


<div class="container-fluid">
    <br>
    <h1 class="display-6">Data Entry</h1>
<div class="card border-info mb-3" style="max-width: 40rem;">

<form method="POST" action="{{ url_for('api.data_entry_params') }}">
    <div class="card-body">
        <p class="card-text">Enter assessment scores:</p>
        <div class="row">
            <div class="mb-3 col">
            <select class="form-select form-select-sm" id="assessmentSelect" name="assessment" required>
            <option value="" selected disabled>Assessment</option>
            {% for assessment in assessments %}
            <option value="{{ assessment }}">{{ assessment }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3 col">
        <select class="form-select form-select-sm" id="periodSelect" name="period" required>
            <option value="" selected disabled>Period</option>
            {% for key, value in periods|dictsort %}
            <option value="{{ key }}">{{ value }}</option>
            {% endfor %}
        </select>
    </div>
    </div>
    <div>
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</div>
</form>

</div>

</div>
<br>
{% endblock %}

app/templates/api/edit_data.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <br>
    <h1 class="display-6">Edit Data</h1>
    <form action="{{ url_for('api.edit_data', assessment_name=assessment_name) }}?period={{ period }}"  method="POST">
        {{ form.hidden_tag() }}
        <br>
        </div>
        <div class="container-fluid">
            {% if data %}
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col" class="align-center">Student</th>
                        {% for component in components %}
                        <th scope="col" class="align-center">{{ component.component_name }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for student, student_data in data.items() %}
                    

                    <tr>
                        <th scope="row">{{ student }}</th>
                        {% for score_data in student_data.scores %}
                        <td>
                            <input class="visually-hidden" type="hidden" name="score_id_{{ score_data.score_id }}" value="{{ score_data.score_id }}">
                            <input class="form-control" type="number" name="student_score_{{ score_data.score_id }}" value="{{ score_data.score_value }}">
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        
        <div class="d-grid gap-2 d-md-block">
            <button class="btn btn-info" type="submit">Submit</button>
            <br>
        </div>
    </div>
    </form>
    {% else %}
    <p>No data for selected assessment and period.</p>
    {% endif %}
</div>
</div>
{% endblock %}

app/templates/api/edit_data_params.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <br>
    <h1 class="display-6">Edit Data</h1>
    
        <div class="card card border-info mb-3" style="max-width: 40rem;">
        


    <form method="POST" action="{{ url_for('api.edit_data_params') }}">
    <div class="card-body ">
        <h4 class="card-title"></h4>
        <p class="card=text">Choose from the options below to edit previously assessment scores.</p>
    <div class="row">
            <div class="mb-3 col">
        <select class="form-select form-select-sm" id="assessmentSelect" name="assessment" required>
            <option value="" selected disabled>Assessment</option>
            {% for assessment in assessments %}
            <option value="{{ assessment }}">{{ assessment }}</option>
            {% endfor %}
        </select>
            </div>
    <div class="mb-3 col">
        <select class="form-select form-select-sm" id="periodSelect" name="period" required>
            <option value="" selected disabled>Period</option>
            {% for key, value in periods.items() %}
                    <option value="{{ key }}">{{ value }}</option>
            {% endfor %}
        </select>
    </div>
        </div>
    <div>
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</div>
</form>

</div>
</div>
<br>

{% endblock %}

app/templates/api/side_nav.html
<aside class="menu">
    <p class="menu-label">Data Entry</p>
    <ul class="menu-list">
        <a class="is-active">Literacy</a>
        <ul>
        <li><a href="{{ url_for('api.data_entry') }}">Predictive Assessment of Reading</a></li>
        <li><a>AimsWebLiteracy</a></li>
        </ul>
        <a class="is-active">Math</a>
        <ul>
        <li><a href="{{ url_for('api.data_entry_math') }}">PNOA</a></li>
        </ul>
        <a class="is-active">Social Emotional</a>
        <ul>
        <li><a>Panorama</a></li>
        <li><a>Daily Check-ins</a></li>
        </ul>
    </li>
   

    <p class="menu-label">Insights</p>
    <ul class="menu-list">
    <li><a>Student</a></li>
    <li><a href="{{ url_for('api.class_dashboard', classroom_id=current_user.get_current_classroom().id) }}">Classroom</a></li>
    <li><a>School</a></li>
    </ul>
</aside>

app/templates/api/tabs.html
<div class="container">
    <h1 class="display-6">Literacy Assessments</h1>
    <!-- Page Tabs -->
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        {% for assessment in gl_assessments %}
        <li class="nav-item">
        </li>
            <a class="nav-link" id="assessment-tab" data-toggle="tab" href="{{ url_for('api.data_entry'), assessment_name={{ assessment }} }}" role="tab" aria-controls="PAR" aria-selected="true"><small class="text-body-secondary"><strong>{{ assessment_name }}</strong></small></a>
        </li>
        {% endfor %}
    </ul>
    <div class="tab-content" id="myTabContent">
        {% for assessment in gl_assessments %}
        <div class="tab-pane fade show active" id="{{ assessment }}" role="tabpanel" aria-labelledby="{{ assessment }}-tab">{% includes 'data_entry.html' %}</div>
        {% endfor %}
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>