app/api/routes.py
import math
import sqlalchemy as sa
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, flash
from flask_login import current_user, login_required
from models import db, AssessmentComponent, AssessmentScore
from forms import AssessmentScoreForm, ComponentForm, EditAssessmentScoreForm
from app.services.charts import *
from app.services.data_analysis import *
from app.services.api_views import *
import numpy as np

api = Blueprint('api', __name__, url_prefix='/api', template_folder='../templates/api')
templates = Blueprint('templates', __name__)

@api.route('/', methods=['GET', 'POST'])
def data_entry_params():
    """landing page for data entry"""
    if request.method == 'GET':
        return render_data_entry_parameters()
    elif request.method == 'POST':
        return process_data_entry_parameters()
    
@api.route('/data_entry/<string:assessment_name>', methods=['GET', 'POST'])
def data_entry(assessment_name):
    """API endpoint for data entry"""
    period = request.args.get('period')
    if request.method == 'GET':
        return render_data_entry_template(assessment_name, period)
    elif request.method == 'POST':
        return process_data_entry_request(assessment_name, period)


@api.route('/data_entry/edit', methods=['GET', 'POST'])
def edit_data_params():
    """Landing page for editing data"""
    if request.method == 'GET':
        return render_edit_data_parameters()
    elif request.method == 'POST':
        return process_edit_data_parameters()

def render_edit_data_parameters():
    """Parameters for editing score data in database"""
    user = current_user
    current_class = user.get_current_classroom()  # returns classroom object
    class_score_data = get_data(current_class.id)

    assessments = class_score_data['assessment_name'].unique()  # assessments already taken
    periods = {1: 'fall', 2: 'winter', 3: 'spring'}
    available_periods = {assessment:[periods] for assessment in class_score_data['assessment_name'] for period in class_score_data['period']}
    # Create a dictionary to hold available periods for each assessment

    return render_template('edit_data_params.html', assessments=assessments, periods=periods, available_periods=available_periods)

def process_edit_data_parameters():
    print(request.form)
    assessment = request.form.get('assessment')
    period = request.form.get('period')
    if assessment and period:
        return redirect(url_for('api.edit_data', assessment_name=assessment, period=period))
    else:
        flash('Please select both an assessment and a period', 'error')
        return redirect(url_for('api.edit_data_params'))

@api.route('/data_entry/edit/<string:assessment_name>', methods=['GET', 'POST'])
def edit_data(assessment_name):
    """API endpoint for editing data"""
    period = request.args.get('period')
    if request.method == 'GET':
        return render_edit_data_template(assessment_name, int(period))
    elif request.method == 'POST':
        return process_edit_data_request(assessment_name, int(period))



@api.route('/classroom/<string:classroom_id>', methods=['GET', 'POST'])
@login_required
def class_dashboard(classroom_id, method='GET'):
    user=current_user
    current_class = user.get_current_classroom()
    classroom_info = current_class.to_dict()
    data = get_data('21-SPA-0')

    math_data = data[(data.subject == 'math')]
    lit_data = data[(data.subject == 'literacy')]
    math_fun_fig= make_funnel(math_data)
    math_bar_fig = make_bar_fig(math_data)
    lit_fun_fig= make_funnel(lit_data)
    lit_bar_fig = make_bar_fig(lit_data)

    figs = [lit_bar_fig, math_bar_fig, lit_fun_fig, math_fun_fig]

    return render_template(template_name_or_list='class_dashboard.html', classroom_info=classroom_info, classroom_id=current_class, figs=figs)

app/authentication/routes.py
import sqlalchemy as sa
from flask import render_template, Blueprint, request, redirect, url_for, flash, session
from werkzeug.middleware.profiler import ProfilerMiddleware
from wtforms.validators import ValidationError
from models import User, Staff, db, login_manager
from forms import UserRegistrationForm, UserLoginForm
from flask_login import login_user, logout_user, login_required, current_user

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@login_manager.user_loader
def load_user(id):
    return db.session.get(User, int(id))


#login route
@auth.route('/login', methods=['GET', 'POST'])
def login():
    '''
    Login user by validating login form (email & password).
    Redirect to profile page if/once logged in.
    '''
    if current_user.is_authenticated:
        return redirect(url_for('main.user', username=current_user.username))
    
    form = UserLoginForm()
    if form.validate_on_submit():
        #create instance of User class, find user by email address
        user = db.session.scalar(
            sa.select(User).where(User.email == form.email.data))

        #validate user's password 
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('auth.login'))

        login_user(user, remember=form.remember_me.data)
        

        flash('Login successful!', 'success')
        
        return redirect(url_for('main.profile', username=user.username))
    
    return render_template('login.html', form=form)


@auth.route('/register', methods=['GET','POST'])
def register():
    form = UserRegistrationForm()

    if form.validate_on_submit():
        staff = db.session.scalar(sa.select(Staff).where(
            Staff.email == form.email.data
            ))
        existing_user = db.session.scalar(sa.select(User).where(
            User.email == form.email.data))
        if staff is None:
            raise ValidationError('Email not recognized, please use an organization email address.')
        elif existing_user is not None:
            flash ('Email already exists, please login.')
            return redirect(url_for('auth.login'))
        else:
            print("Creating new user") 
            user = User(
                email= form.email.data,
                first_name=form.first_name.data,
                last_name=form.last_name.data
            )

            user.set_id()
            user.set_password(form.password.data)
            user.user_profile()
            user.staff_member = True
            user.staff_id = staff.id
            

            print(f'User instance: {user}') 

            db.session.add(user)
            db.session.commit()

            login_user(user)

            #success message
            flash(f'Account created for {user.email}!', 'success')
            return redirect(url_for('main.profile', username=user.username))
    else:
        return render_template('register.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout successful!', 'success')
    return redirect(url_for('main.index'))

    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Student Insights</title>
<link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/zephyr/bootstrap.min.css
" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <!-- NAVBAR -->

<nav class="navbar navbar-expand bg-dark" data-bs-theme="dark">
    <div class="container-fluid">

    <!-- Brand Image -->
    <span class="navbar-brand">
        <img src="/static/images/insights_light.png" alt="Student Insights" width="90" height="25">
    </span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto">
{% if current_user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('api.data_entry_params') }}">
        Data Entry</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('api.edit_data_params') }}">
        Edit Data</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('api.class_dashboard', classroom_id=current_user.get_current_classroom().id) }}"><i class="fa fa-dashboard" aria-hidden="true"></i>
        Insights</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.profile', username=current_user.username) }}">
        Profile</a>
    </li>
    </ul>
        <a class="btn btn-sm btn-light me-2" type="button" href="{{ url_for('auth.logout') }}">Logout</a>
        <div class="dark-mode-toggle">
            <i id="darkModeIcon" class="bi bi-moon"></i> 
        </div>
        {% else %}
        <button class="btn btn-sm btn-outline-secondary" type="button" href="{{ url_for('auth.register') }}">
        Register</button>
{% endif %}
</div>
    </div>
</nav>
<script>
    document.getElementById('darkModeIcon').addEventListener('click', function () {
    this.classList.toggle('bi-moon');
    this.classList.toggle('bi-sun');
    let theme = document.documentElement.getAttribute('data-bs-theme');
    if (theme === 'dark') {
    document.documentElement.removeAttribute('data-bs-theme');
    } else {
    document.documentElement.setAttribute('data-bs-theme', 'dark');
    }
});
</script>

{% block content %}
{% endblock %}

</body>

</html>

app/templates/dataframe.html
{% extends 'base.html' %}

{% block content %}

<h1>Data</h1>
<table>
    <thead>
        <tr>
            {% for column in df.columns %}
            <th>
                {{ column }}
            </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for index, row in df.iterrows() %}
        <tr>{% for value in row %}
            <td>{{ value }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}